# Generated by Django 4.0.6 on 2022-10-23 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0002_alter_commentpost_likes_alter_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='root',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Post.post'),
        ),
    ]
