# Generated by Django 4.0.6 on 2022-10-04 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Socket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='chat'),
        ),
    ]
